### ISSUE TITLE
Feature request: File drop on mono x page

### ISSUE THREAD

**Issue by JobyB** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#1]
Great tool, just got it up and running, busy trying to break it :) but one thing I'd like to request, could you add the "drop file here" box to the momo x page, then you can just sit on one page, view the cam, view the printer status, and drop new file on to it all in one place.

Thanks

Joby

**Comment by tds2021** [comment]
The file lists on each page are from different sources and I do not want to cause confusion for users having two lists on the same page that may not match.  I am not duplicating the upload on the printer page.
