### ISSUE TITLE
File transfer to Zero

### ISSUE THREAD

**Issue by PrCRTL** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#13]
with Version 2.3.1 the possibility to move Files to the Zero is not possible anymore when Mono is switched OFF
To copy it over the explorer is possible, like to have the drag and drop available again when Mono is OFF  :)

**Comment by tds2021** [comment]
This has been addressed in 2.4.0-beta.

https://github.com/tds2021/Pi-Zero-W-Smart-USB-Flash-Drive/releases/tag/2.4.0-beta
