### ISSUE TITLE
Shutdown button does nothing

### ISSUE THREAD

**Issue by Hesi-Re** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#17]
Raspberry Pi continues running after clicking the shutdown button

**Comment by tds2021** [comment]
This will be fixed in the next version I’m testing now.

**Comment by tds2021** [comment]
This has been addressed in 2.4.0-beta.

https://github.com/tds2021/Pi-Zero-W-Smart-USB-Flash-Drive/releases/tag/2.4.0-beta
