### ISSUE TITLE
Question UART interface to the pi  for example Anycubic Photon S etc.

### ISSUE THREAD

**Issue by raindancer2204** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#19]
Hi,

I was referred to the link here through a forum.

I own an Anycubic Phonton **S.**

I was first interested in this project where the Anycubic Photon (old version) can be controlled via the **UART** interface.
https://github.com/Chasedog98/PhotonPi

So far I haven't received any feedback from the developer about my Question on the ISSUES.

Is there a possibility that you might also implement this feature? I think the most Printers have UART support.

And pulling 3 cables on the PI shouldn't be a problem for most of them.

I will now try out your project here.

Reagards

**Comment by tds2021** [comment]
Sorry, I’m not a hardware guy, and I would have no way to test any of it. I think this best accomplished by someone who has one of these printers. I would not feel comfortable taking it on. 

Sent while walking into stuff

Troy
