### ISSUE TITLE
Support of the Anycubic Mono SE with WLAN

### ISSUE THREAD

**Issue by raindancer2204** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#20]
Hi,

I now have the next question, you got the Anycubic Photon Mono X to work via your control.

The Anycubic Mono **SE** also has the WLAN module and the app control.

You have tested that. Can you also add the Mono SE via your smartphone app?

To what extent do you estimate that the configurations are the same?

I know that you do not have such a device, but would it be conceivable that you could support the device with additional work?

Thank you Raini

P.S: The project with the Photon S via serial does not work. Have done several tests with it.

**Comment by tds2021** [comment]
AnyCubic Mono SE support has already been added to ver. 2.4.2 BETA.  It has been tested by a different users and they reported it worked.  YOu’ll need to download the img file and re-flash your SD card to make this jump.

https://github.com/tds2021/Pi-Zero-W-Smart-USB-Flash-Drive/releases/tag/2.4.2-beta

Troy
