### ISSUE TITLE
Feature Request Time Management

### ISSUE THREAD

**Issue by PrCRTL** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#22]
the print status showes the remaining print time only....
To have a perfect print time view I would appreciate to expand it with

- the initial estimated Print time (otherwise only recoverable by restarting the print)
- elapsed print time 

thanks and best regards

**Comment by tds2021** [comment]
The print time remaining is what the printer calculates and makes available. It is not something I determine. The original time is not something the printer exposes. 

Sent while walking into stuff

Troy
