### ISSUE TITLE
stripes-artifacts

### ISSUE THREAD

**Issue by Sadhaka87** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#27]
In version v2.4.4-beta, there was probably a disk read error several times. This was expressed in the fact that at a certain height, the entire surface of the screen began to light up with stripes-artifacts. This spoils the film very much and needs to be cleaned for a long time. Moreover, all this is displayed on the screen of the printing process. Has anyone encountered this problem? When printing from a regular flash drive or with firmware version 2.3.0, this did not happen. But version 2.3.0 is very slow and you have to manually restart the printer all the time. As a result, now I use a regular flash drive.

**Comment by tds2021** [comment]
I could not reproduce this.  Can you download a copy of 2.4.4 (not beta) and try it?
