### ISSUE TITLE
MonoX Console empty

### ISSUE THREAD

**Issue by PrCRTL** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#31]
when start printing again around 2 weeks ago, connection to MonoX console takes much longer as before ( same Version 2.4.4 BETA) and a few days later after connected the screen is simply empty.... the only thing changed on my system was and Win10 Update.... 
Sorry but I cant be more precisely... see on my picture what I see after connected to the printer...

![grafik](https://user-images.githubusercontent.com/7194561/124660610-b8b8fa80-dea6-11eb-9a91-3882b1651b29.png)

**Comment by discojon** [comment]
Same thing here.  It worked exactly once when i first set it up.  But now it is completely blank as you indicate.

**Comment by discojon** [comment]
Were you able to get this resolved or do i just need to reflash?

**Comment by PrCRTL** [comment]
Hi, yes, it is solved. Seems it was an issue with an Win10 Update.ThanksBest regards


Gesendet von Yahoo Mail für iPhone


Am Samstag, September 18, 2021, 03:21 schrieb discojon ***@***.***>:




Were you able to get this resolved or do i just need to reflash?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by klim123123** [comment]
I have exactly the same problem. Just blank page after connecting... 
It worked once or two and now only blank page.
I tried Firefox, Chome, Edge, iPhone and Android. Same problem with blank page.

My printer is available using iOS app no problems.

![image](https://user-images.githubusercontent.com/64870895/148865755-c6665a74-62a9-4ddc-baf5-068372be0e49.png)

![image](https://user-images.githubusercontent.com/64870895/148865780-342a3b95-929d-48a5-9864-3745e3a25e19.png)

**Comment by klim123123** [comment]
It was a problem with my UniFi network. For some reason it's blocked traffic to MonoX from everywhere buy iPhone.
It would be nice to have at least error message on this screen.
