### ISSUE TITLE
Feature: Time lapse

### ISSUE THREAD

**Issue by olituks** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#32]
Could be interesting to setup a time lapse system.
At least an extra partition with pictures can be downloaded and assembled with ffmpeg on a more powerful pc.
Just an idea of course.
P.S. great job :)

**Comment by tds2021** [comment]
I have looked at this in the past.  Unlike a filament printer where you can see the model all the time, a resin printer is submerged most of the time.To produce a time lapse, you really need to take the shot while the printer is at the "top" of the cycle.  AnyCubic does not expose a status for the carage position. Without that, it would be very difficult to guess at the correct time to take the picture and then assemble a video.  

This is not something I think I could be successful at.
