### ISSUE TITLE
Does not mount

### ISSUE THREAD

**Issue by fiveorders** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#33]
Hello, thank you for this ready to use image. 

I can see it as a network drive on my mac but USB does not mount. It does not mount to TFT70 LCD screen as well. 

How can I make it mount like a USB stick?

**Comment by fiveorders** [comment]
And also there is an upgrade button on top right but it goes no where. Thanks

![Screenshot 2021-07-23 at 20 56 38](https://user-images.githubusercontent.com/13808989/126834834-3c5b137e-7809-4dfd-90b1-100e6450c531.png)

**Comment by tds2021** [comment]
I'm not sure what version you are using, but I would download the 2.4.4 image and start from a clean install.  As for the mounting, make sure you are using the correct per port.  Those are the only ports that support OTG.
