### ISSUE TITLE
Conflicting information in Readme.me

### ISSUE THREAD

**Issue by brownt12684** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#37]
For "Tested Configuration : Raspberry Pi Zero W" Readme.md states,
"NOTE: You must use the "pwr" port to conenct to the printer. The "usb" port does not support USB OTG."

Further under "Powering the Raspberry Pi", readme.md states,
"You can connect your 3D printer into the Pi Zero W USB port, not the PWR IN port"
 
 Link to image does not forward to latest release.
 "Create SD Card
Step 1. Download the latest release."

**Comment by tds2021** [comment]
I fixed the link.  that you for catching that.  However, I think the prose details are correct.  The first statement is in the Zero W sect and the second is in the Pi 4 section.  I'll re-verify those, but they are not the same ports for each device.
