### ISSUE TITLE
Known Issue: Starting a print job may load the wrong file. 

### ISSUE THREAD

**Issue by tds2021** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#4]
By sorting the file list, in version 2.3.0, on the Mono X continue page, a bug appears to have been introduced. The printer may load the incorrect file. I’ll fix this over the weekend.

**Comment by JobyB** [comment]
This hit me today :(

**Comment by lollokara** [comment]
Currently a fix is to delete all the files but the one you need to print. I will try to have a look at the code and see if I can get some sort of fix

**Comment by tds2021** [comment]
The issue has been resolved and a patch is available.  Install instructions are here:

https://github.com/tds2021/Pi-Zero-W-Smart-USB-Flash-Drive/releases/tag/2.3.1-patch

I will create a new img file as well, but that take a few hours.

I belive this is resolved.

**Comment by JobyB** [comment]
Great thanks, just downloaded it and installed, love the other little changes like the fav.icon I'll test out the fix a bit later when I'm not printing something :)

**Comment by tds2021** [comment]
2.3.1 patch resolved this.  Confirmed by two testers
