### ISSUE TITLE
Pi zero 2 W

### ISSUE THREAD

**Issue by Zw3rg85** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#40]
Hello how can i use a pi zero 2w?
is version 2.4 down?

Thank you

**Comment by tds2021** [comment]
I do not have access to a pi zero 2w so it has not been tested. However, I would probably surprised if and hardware changes in the pi would matter. As for the version 2.4.4 is the current version and has been stable. What issue are you having?

**Comment by Zw3rg85** [comment]
Hello. Were i can Download 2.2.4

Mit freundlichen Grüßen
Alexander Beck

E-Mail: ***@***.***
Mobil: 0151 - 22681416

Alexander Beck EDV - DESIGN - PRINT - LASER GRAVUR
Schulweg 4, 69412. Eberbach Geschäftsführer: Alexander Beck
USt-Id-Nr.: DE316724113
www.Beck-Eberbach.de

Am 2. Dez. 2021, 14:01 +0100 schrieb Troy S ***@***.***>:

**Comment by tds2021** [comment]
https://github.com/tds2021/Pi-Zero-W-Smart-USB-Flash-Drive/releases

**Comment by Zw3rg85** [comment]
Tank you
I will test the Version with Zero w 2

Mit freundlichen Grüßen
Alexander Beck

E-Mail: ***@***.***
Mobil: 0151 - 22681416

Alexander Beck EDV - DESIGN - PRINT - LASER GRAVUR
Schulweg 4, 69412. Eberbach Geschäftsführer: Alexander Beck
USt-Id-Nr.: DE316724113
www.Beck-Eberbach.de

Am 2. Dez. 2021, 14:11 +0100 schrieb Troy S ***@***.***>:

**Comment by mnrivera210** [comment]
Hey I loaded the image onto the Pi W 2 and it will not boot. Anyway to manually install this to a clean image?

**Comment by Zw3rg85** [comment]
Hello I Have Testet 2.4.4
https://github.com/tds2021/Pi-Zero-W-Smart-USB-Flash-Drive/releases/tag/2.4.4

Works Well With Pi Zero 2 W

**Comment by tds2021** [comment]
Not easily. However, I ordered a Zero2w this morning. When it get here I’ll see if I can make an update mage that works with the new hardware. 

Sent while walking into stuff

Troy

**Comment by Zw3rg85** [comment]
![pi2](https://user-images.githubusercontent.com/95000632/144521261-041ed89f-85dd-46fa-9fe9-a509100b74e0.JPG)

**Comment by tds2021** [comment]
That's great news!
